export const employeePositions = [
  "Software Engineer",
  "Product Manager",
  "Designer",
  "QA Engineer",
  "DevOps Engineer",
  "HR Specialist",
  "Marketing Manager",
  "Sales Executive",
  "Customer Support",
  "Data Analyst",
  "Business Analyst",
  "Technical Lead",
  "Project Manager",
  "Content Strategist",
  "UX Researcher",
  "Frontend Developer",
  "Backend Developer",
  "Full Stack Developer",
  "Mobile Developer",
  "Machine Learning Engineer",
  "Data Scientist",
  "IT Support Specialist",
  "Network Administrator",
  "Security Analyst",
  "Database Administrator",
  "Cloud Engineer",
  "Systems Administrator",
  "Scrum Master",
  "Operations Manager",
  "Financial Analyst",
  "Accountant",
  "Legal Counsel",
];

export const employeeDepartments = [
  "Engineering",
  "Product",
  "Design",
  "Quality Assurance",
  "DevOps",
  "Human Resources",
  "Marketing",
  "Sales",
  "Customer Support",
  "Data Science",
  "Business Analysis",
  "Project Management",

  "Content Strategy",

  "User Experience",
  "Information Technology",
  "Network Administration",
  "Security",
];

export const employeeStatuses = [
  "Active",
  "Inactive",
  "On Leave",
  "Terminated",
];
